# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "weibo"
name = "weibo"
url = "https://weibo.com/meroco"

[social.params]
icon = "brand-weibo"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/meroco_moe"

[social.params]
icon = "brand-twitter"
