# Configure main menu and social menu
[[main]]
identifier = "home"
name = "主页"
url = "/"
[main.params]
icon = "home"
newtab = false


[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/meroco_moe"

[social.params]
icon = "brand-twitter"
